AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shorturl-backend
  
  ShortURL Service Backend running on Lambda@Edge
  
Globals:
  Function:
    Timeout: 3

Resources:
  ShortURLBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: shorturl-backend/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  ShortURLBackendFunction:
    Description: "ShortURL Backend Function Arn"
    Value: !GetAtt ShortURLBackendFunction.Arn
